services:

  mongo:
    image: mongo:7.0
    restart: always
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: login
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongo_data:
